### ISSUE TITLE
Unable to set step color when hasRoundedCorner is false

### ISSUE THREAD

**Issue by andrijailic** [lcsvcn/cool-stepper-reloaded#4]
**Describe the bug**
Although documentation is missing description about this, there is a **_stepColor_** option in _CoolStepperConfig_ and it is only applied if _hasRoundedCorner_ property of _CoolStepper_ widget is enabled. I guess this should be applied regardless of rounding.

**Expected behavior**
If defined, _stepColor_ should be applied regardless of _hasRoundedCorner_ value.

**Information (please complete the following information):**
 - Device: Pixel 2 API 30
 - Platform: mobile
 - Flutter version: 2.8.1
 - Package version 3.2.5

**Additional context**
It seems inconsistent that some of the options are located inside **CoolStepperConfig** class but others are still inside **CoolStepper** itslef, like _contentPadding_, _showErrorSnackbar_, _isHeaderEnabled_ and _hasRoundedCorner_.

**Comment by lcsvcn** [comment]
Please send inside the content the color that you need. Like this:


```
CoolStep(
        title: 'Select your role',
        subtitle: 'Choose a role that better defines you',
        alignment: Alignment.center,
        content: Container(
          color: Color.red,
          child: Row(
            children: <Widget>[
              _buildSelector(
                context: context,
                name: 'Writer',
              ),
              SizedBox(width: 5.0),
              _buildSelector(
                context: context,
                name: 'Editor',
              ),
            ],
          ),
        ),
      ),
```
